"""
Emit a complete .kicad_pcb from the layout plan, without KiCad.

Normally the board is generated by jaiba-kicad-controlboard.py running inside
KiCad's Scripting Console, which needs the `pcbnew` module (shipped with KiCad,
not with Python). This script produces the same board straight from the plan in
jaiba_board_layout.py, so the project can be regenerated and geometry-checked
anywhere -- including CI or a machine with no KiCad install.

Footprints are read from the project-local library in
kicad-control-board/jaiba.pretty/, which makes the project self-contained: it no
longer depends on KiCad's system libraries or on a hard-coded install path.

Run:  python3 tools/emit_board.py [output.kicad_pcb]
"""

import copy
import os
import sys
import uuid

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import kicad_sexpr as ks          # noqa: E402
import jaiba_board_layout as L    # noqa: E402

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIBDIR = os.path.join(REPO, "kicad-control-board", "jaiba.pretty")
DEFAULT_OUT = os.path.join(REPO, "kicad-control-board", "kicad-control-board.kicad_pcb")

# Board header (stackup, design rules, plot parameters), captured verbatim from
# a board KiCad itself wrote. It is embedded rather than read back from the
# output file so the emitter stays idempotent: treating the generated board as
# its own template would make every run depend on the previous one, and would
# break as soon as the file's format version changed.
BOARD_TEMPLATE = r'''
(kicad_pcb
	(version 20241229)
	(generator "jaiba-emit_board")
	(generator_version "9.0")
	(general
		(thickness 1.6)
		(legacy_teardrops no)
	)
	(paper "A4")
	(layers
		(0 "F.Cu" signal)
		(2 "B.Cu" signal)
		(9 "F.Adhes" user "F.Adhesive")
		(11 "B.Adhes" user "B.Adhesive")
		(13 "F.Paste" user)
		(15 "B.Paste" user)
		(5 "F.SilkS" user "F.Silkscreen")
		(7 "B.SilkS" user "B.Silkscreen")
		(1 "F.Mask" user)
		(3 "B.Mask" user)
		(17 "Dwgs.User" user "User.Drawings")
		(19 "Cmts.User" user "User.Comments")
		(21 "Eco1.User" user "User.Eco1")
		(23 "Eco2.User" user "User.Eco2")
		(25 "Edge.Cuts" user)
		(27 "Margin" user)
		(31 "F.CrtYd" user "F.Courtyard")
		(29 "B.CrtYd" user "B.Courtyard")
		(35 "F.Fab" user)
		(33 "B.Fab" user)
		(39 "User.1" user)
		(41 "User.2" user)
		(43 "User.3" user)
		(45 "User.4" user)
	)
	(setup
		(pad_to_mask_clearance 0)
		(allow_soldermask_bridges_in_footprints no)
		(tenting front back)
		(pcbplotparams
			(layerselection 0x00000000_00000000_55555555_5755f5ff)
			(plot_on_all_layers_selection 0x00000000_00000000_00000000_00000000)
			(disableapertmacros no)
			(usegerberextensions no)
			(usegerberattributes yes)
			(usegerberadvancedattributes yes)
			(creategerberjobfile yes)
			(dashed_line_dash_ratio 12.000000)
			(dashed_line_gap_ratio 3.000000)
			(svgprecision 4)
			(plotframeref no)
			(mode 1)
			(useauxorigin no)
			(hpglpennumber 1)
			(hpglpenspeed 20)
			(hpglpendiameter 15.000000)
			(pdf_front_fp_property_popups yes)
			(pdf_back_fp_property_popups yes)
			(pdf_metadata yes)
			(pdf_single_document no)
			(dxfpolygonmode yes)
			(dxfimperialunits yes)
			(dxfusepcbnewfont yes)
			(psnegative no)
			(psa4output no)
			(plot_black_and_white yes)
			(sketchpadsonfab no)
			(plotpadnumbers no)
			(hidednponfab no)
			(sketchdnponfab yes)
			(crossoutdnponfab yes)
			(subtractmaskfromsilk no)
			(outputformat 1)
			(mirror no)
			(drillshape 1)
			(scaleselection 1)
			(outputdirectory "")
		)
	)
'''
TEMPLATE_KEYS = ("general", "paper", "layers", "setup")


def fmt(v):
    """Format a number the way KiCad does (no trailing zeros)."""
    if isinstance(v, str):
        return v
    if float(v) == int(v):
        return str(int(v))
    return f"{v:.6f}".rstrip("0").rstrip(".")


def load_library():
    lib = {}
    for fn in sorted(os.listdir(LIBDIR)):
        if fn.endswith(".kicad_mod"):
            fp = ks.parse(open(os.path.join(LIBDIR, fn), encoding="utf-8").read())
            lib[fp[1]] = fp
    return lib


def set_child(node, key, value):
    for i, item in enumerate(node):
        if isinstance(item, list) and item and item[0] == key:
            node[i] = value
            return
    node.append(value)


def instantiate(libfp, item, netnum):
    """Clone a library footprint into a placed, netted board footprint."""
    out = [libfp[0], libfp[1],
           ["layer", ks.Quoted("F.Cu")],
           ["uuid", ks.Quoted(str(uuid.uuid4()))],
           ["at", fmt(item["x"]), fmt(item["y"]), fmt(item.get("rot", 0))]]

    for ch in libfp[2:]:
        if not isinstance(ch, list):
            continue
        key = ch[0]
        if key in ("layer", "at", "uuid", "net"):
            continue
        node = copy.deepcopy(ch)
        if key == "property":
            set_child(node, "uuid", ["uuid", ks.Quoted(str(uuid.uuid4()))])
            if node[1] == "Reference":
                node[2] = ks.Quoted(item["ref"])
            elif node[1] == "Value":
                node[2] = ks.Quoted(item["value"])
        elif key == "pad":
            set_child(node, "uuid", ["uuid", ks.Quoted(str(uuid.uuid4()))])
            # existing net element was already dropped by the clone loop above
            net = item["nets"].get(node[1])
            if net:
                node.append(["net", str(netnum[net]), ks.Quoted(net)])
        out.append(node)
    return out


def links_by_ref(plan):
    """Nets that reach a footprint only through a jumper (ratsnest) link."""
    out = {}
    for ref, pin, net in plan["links"]:
        out.setdefault(ref, {})[pin] = net
    return out



# KiCad's parser requires these values to be quoted strings. An unquoted one
# produces a file that round-trips happily through our own reader but that KiCad
# refuses to open, with an error that names only a line number -- so check
# before writing rather than after someone tries to load it.
QUOTED_KEYS = {"generator", "generator_version", "descr", "tags", "uuid",
               "model", "pinfunction", "pintype"}


def needs_quotes(value):
    """Would KiCad's tokeniser choke on this written bare?

    It accepts a bare *symbol* almost anywhere -- `(layer F.Cu)` and bare uuids
    load fine, which is why unquoted ones went unnoticed for so long. What it
    cannot accept is a value that tokenises as a NUMBER where it wants a symbol:
    `(generator_version 9.0)` is the error this check exists for.
    """
    if not isinstance(value, str) or isinstance(value, ks.Quoted):
        return False
    if any(c.isspace() for c in value):
        return True
    try:
        float(value)
        return True
    except ValueError:
        return False


def lint_quoting(node, where="kicad_pcb[0]", problems=None):
    """Walk the tree and report values KiCad requires to be quoted strings."""
    if problems is None:
        problems = []
    if not isinstance(node, list) or not node:
        return problems
    key = node[0] if isinstance(node[0], str) else None

    def flag(what, value):
        if needs_quotes(value):
            problems.append(f"{where}/{what}: {value!r} written bare tokenises wrong")

    if key == "layers":
        for i, v in enumerate(node[1:], 1):
            flag(f"layers[{i}]", v)
    elif key == "layer" and len(node) > 1:
        flag("layer", node[1])
    elif key == "uuid" and len(node) > 1:
        if not isinstance(node[1], ks.Quoted):
            problems.append(f"{where}/uuid: {node[1]!r} must be a quoted uuid")
    elif key == "generator_version" and len(node) > 1:
        # the one KiCad definitely writes as a string, and the one that bit us
        if not isinstance(node[1], ks.Quoted):
            problems.append(f"{where}/generator_version: {node[1]!r} must be quoted")
    elif key in QUOTED_KEYS and len(node) > 1:
        flag(key, node[1])
    elif key in ("footprint", "pad") and len(node) > 1:
        flag(key + "[1]", node[1])
    elif key == "property":
        for i in (1, 2):
            if i < len(node):
                flag(f"property[{i}]", node[i])
    elif key == "net" and len(node) > 2:
        flag("net[2]", node[2])

    for i, ch in enumerate(node):
        if isinstance(ch, list):
            lint_quoting(ch, f"{where}/{key or '?'}[{i}]", problems)
    return problems


def emit(plan, out_path):
    lib = load_library()
    netnum = L.collect_nets(plan)
    extra = links_by_ref(plan)

    template = ks.parse(BOARD_TEMPLATE)
    root = ["kicad_pcb",
            ["version", "20241229"],
            ["generator", ks.Quoted("jaiba-emit_board")],
            ["generator_version", ks.Quoted("9.0")]]
    for key in TEMPLATE_KEYS:
        node = ks.child(template, key)
        if node:
            root.append(copy.deepcopy(node))

    root.append(["net", "0", ks.Quoted("")])
    for name, num in netnum.items():
        root.append(["net", str(num), ks.Quoted(name)])

    for item in plan["footprints"]:
        if item["name"] not in lib:
            raise SystemExit(f"footprint {item['name']!r} missing from {LIBDIR}")
        merged = dict(item)
        merged["nets"] = {**item["nets"], **extra.get(item["ref"], {})}
        root.append(instantiate(lib[item["name"]], merged, netnum))

    for t in plan["tracks"]:
        if "x1" not in t:
            continue
        root.append(["segment",
                     ["start", fmt(t["x1"]), fmt(t["y1"])],
                     ["end", fmt(t["x2"]), fmt(t["y2"])],
                     ["width", fmt(t.get("width", L.TRACK_W))],
                     ["layer", "F.Cu"],
                     ["net", str(netnum[t["net"]])],
                     ["uuid", ks.Quoted(str(uuid.uuid4()))]])

    for x1, y1, x2, y2 in plan["edges"]:
        root.append(["gr_line",
                     ["start", fmt(x1), fmt(y1)],
                     ["end", fmt(x2), fmt(y2)],
                     ["stroke", ["width", fmt(L.EDGE_W)], ["type", "solid"]],
                     ["layer", ks.Quoted("Edge.Cuts")],
                     ["uuid", ks.Quoted(str(uuid.uuid4()))]])

    root.append(["embedded_fonts", "no"])

    problems = lint_quoting(root)
    if problems:
        print("REFUSING TO WRITE -- values KiCad requires to be quoted are not:")
        for msg in problems[:20]:
            print("   " + msg)
        if len(problems) > 20:
            print(f"   ... and {len(problems) - 20} more")
        raise SystemExit(1)

    ks.dump_file(root, out_path)
    return netnum


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_OUT
    plan = L.plan()
    netnum = emit(plan, out)
    print(f"wrote {os.path.relpath(out, REPO)}")
    print(f"  {plan['width']} x {plan['height']} mm, "
          f"{len(plan['footprints'])} footprints, {len(netnum)} nets, "
          f"{len([t for t in plan['tracks'] if 'x1' in t])} segments, "
          f"{len(plan['edges'])} edge cuts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
